### ISSUE TITLE
是否考虑把iOS 和 Android 和到一起?

### ISSUE THREAD

**Issue by buhe** [beefe/react-native-wechat-android#1]
Awesome project!

**Comment by shexiaoheng** [comment]
好建议，有这个打算，我们已经思考过这个问题，正准备去做。

**Comment by shexiaoheng** [comment]
@buhe 我尝试了下，感觉还是Native层代码还是分开好些，可以在JS层封装到一块

**Comment by buhe** [comment]
ok,确实为了项目管理方便分开会好一点。但是 react native 的比较好的实践确实是放到一起。尤其用npm分发的时候，如果还需要执行 pod install 和 gradle build 就不太方便了。
这方面可以参考下 :http://ljinkai.github.io/2015/09/21/facebook-react-native-android/

不过现在也很赞了，过阵子正好要用，点个赞!

**Comment by buhe** [comment]
引用那篇文章:
学到的另外一课是在分开的iOS和Android代码仓库工作是一件困难的事情，尽管使用了大量的工具和自动化。在构建APP的过程中，Facebook用过这样的模式，我们所有构建的自动化和开发进程都建立并围绕着它。然而，对于产品来说，用一份共享的JavaScript代码库，这种方式并不好。幸运的是，Facebook已经对所有平台都统一了代码库 - 只需要一份JavaScript的拷贝，同步那样的方式已经成为了过去。

**Comment by buhe** [comment]
另外一个挑战是怎么管理源代码的问题。Android和iOS的代码库在Facebook两个不同仓库。广告管理工具的iOS源代码在iOS仓库，Android版本的代码在Android的代码库。举例来说，像iOS版本的代码，我们想用一些Facebook的Android的依赖库，这些库却在Android的代码库存放。另外，Android的APP所有的编译工具，自动化，以及引入的其它插件都在Android的仓库。基于上面，Android的这些app要求重构这些已经存在的iOS代码来抽象具体平台的组件来调用各自的文件。我们是可以直接合并两个版本的代码到一起。但是这种方式却是我们不能接受的。
最后，我们决定指定iOS库为事实上的源代码库，因为iOS版本已经相对稳定。我们设定了定时任务许多次一天来同步iOS的JavaScript到Android的代码库。我们不鼓励在Android版本提交JavaScript代码，如果提交也是在iOS版本同步的提交一份。如果同步代码发现代码有差异，会记录一个任务用来进行后续的检查。
我们让iOS仓库的JavaScropt打包成可以在Android版本上运行的代码。这样我们的产品开发人员就可以接触到尽可能多的JavaScript代码而没有原生代码，也可以直接在iOS仓库直接修改和调试两个版本的代码。但是如果要构建Android的APP还是需要在Android仓库来执行，同样的操作也会在iOS APP - 测试两个平台的不同需要大量的额外工作。为了提高JavaScript开发者的工作流程，我们同样构建了脚本来下载合适的来自整合服务器的原生文件。对于大部分开发者来说就不需要复制一份Android的代码库了 - 他们就可以在iOS代码库开发完整的JavaScript代码，并且能比在Facebook的web流程中更快速的进行迭代。
