### ISSUE TITLE
引入对象是undefined

### ISSUE THREAD

**Issue by xuezier** [beefe/react-native-wechat-android#10]
![image](https://cloud.githubusercontent.com/assets/7692708/18340824/b21a6870-75d9-11e6-9d12-4e0e744fc33d.png)
正常编译通过，但是无法引用

**Comment by xuezier** [comment]
![image](https://cloud.githubusercontent.com/assets/7692708/18340841/d381bb62-75d9-11e6-97de-1af8e1efb3fc.png)

**Comment by shexiaoheng** [comment]
你需要在以下3个文件中加入一些代码才能使用本组件

##### android/settings.gradle

```
include':react-native-wechat-android'       // 需要添加的代码
project(':react-native-wechat-android').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-wechat-android/android')       // 需要添加的代码
```

##### android/app/build.gradle

```
dependencies {
    compile project(':react-native-wechat-android')     // 需要添加的代码
}
```

##### MainApplication

```
@Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new WeChatPackage()       // 需要添加的代码
            );
        }
```

**Comment by shexiaoheng** [comment]
@xuezier 解决了吗？

**Comment by xuezier** [comment]
解決了，但有點不一樣，最新的react-native把MainApplication.java拆成了MainApplication.java和MainApplication.java兩個文件，我用rnpm link react-native-wechat-android 所有配置都正確，但是getPackages()被放到了MainApplication.java中，所以還要到MainApplication.java裏面手動修改文件

``` java
@Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new WeChatPackage()       // 需要添加的代码
            );
        }
```

**Comment by xuezier** [comment]
跟你上面描述的差不多

**Comment by shexiaoheng** [comment]
react-native已经把rnpm集成了，不要再用`rnpm link`这条命令了，直接使用`react-native link`即可，文档一直没更新，误导你了，过段时间我更新下文档
