### ISSUE TITLE
点击分享一闪而过是什么鬼？

### ISSUE THREAD

**Issue by ouyangdxq** [beefe/react-native-wechat-android#13]
点击分享一闪而过是什么鬼？

**Comment by shexiaoheng** [comment]
检查你的签名

**Comment by mataoct** [comment]
微信的签名是指md5值，而不是rsa或sha1的值，而且，还要去掉冒号，还要转换成小写，这样可能还会失败最好重启一下手机，然后就好了； 是不是很想大喊一句微信是SB

**Comment by iineva** [comment]
@mataoct thanks, it's work for me!

**Comment by shexiaoheng** [comment]
有工具包提供的。。。。。。
[微信签名工具下载](https://res.wx.qq.com/open/zh_CN/htmledition/res/dev/download/sdk/Gen_Signature_Android2.apk)，貌似没有复制功能，可能需要手打签名值；也可以下载[新浪的签名工具](https://github.com/mobileresearch/weibo_android_sdk/blob/master/app_signatures.apk)，有复制按钮，比较方便。
