### ISSUE TITLE
不理解我哪里配置的有问题，所有的callback中返回参数都是null

### ISSUE THREAD

**Issue by xuanheScript** [beefe/react-native-wechat-android#14]
例如注册微信或者isWXAppInstalled后都只是返回null

**Comment by shexiaoheng** [comment]
看[isWXAppInstalled(callback)](https://github.com/beefe/react-native-wechat-android#iswxappinstalledcallback)的文档
callback : 回调(err,res)    第一个参数是null证明没错误，第二个参数是结果
