### ISSUE TITLE
为什么删我的评论？是因为你的回复被 20+ 用户点 👎 吗？

### ISSUE THREAD

**Issue by justjavac** [beefe/react-native-wechat-android#19]
![tim 20170518193822](https://cloud.githubusercontent.com/assets/359395/26231984/626dfe04-3c85-11e7-866e-bf2c6404a88c.png)

![2](https://cloud.githubusercontent.com/assets/359395/26231987/6687ba02-3c85-11e7-9ec3-dec05a13a493.png)

是因为你的回复被 20+ 用户点 👎 吗？

**Comment by xiaoyann** [comment]
@justjavac 不好意思，发现项目中的问题并提 PR 我们应该是非常欢迎和感激的，@shexiaoheng 的这些做法确实有点冲动了，他已经退出了这个组织。

**Comment by xwenliang** [comment]
我日哦，他把仓库清空了。。。幸亏他没有删库权限

**Comment by chunyanzhu** [comment]
吃瓜群众路过

**Comment by justjavac** [comment]
居然回复我：“那你别用啊！”
真是优越感爆棚啊
