### ISSUE TITLE
我打包了应用，没有用混淆，发现没办法用微信进行登录了。不能唤起微信

### ISSUE THREAD

**Issue by buhe** [beefe/react-native-wechat-android#3]
有什么好办法定位一下么
谢谢

**Comment by buhe** [comment]
好吧。 重新安装一下好了。 权当偶现问题记录下吧

**Comment by buhe** [comment]
额 是这样的。 微信在登录账户的情况下没有办法 唤醒。 
在未登录状态可以唤醒。 但是唤醒后登录账户。 回到react native 应用。 还是没有正确的登录。
有什么思路可以定位下么

**Comment by buhe** [comment]
打出来的 debug apk 是可以的。 release apk ，无论是否签名都不行

**Comment by buhe** [comment]
我的问题. debug 和 release 的wechat 签名不同。 需要重新更新 官网配置

**Comment by shexiaoheng** [comment]
:+1:
