### ISSUE TITLE
点击登录或者分享等无反应

### ISSUE THREAD

**Issue by pppluto** [beefe/react-native-wechat-android#4]
登录无反应可能是没有认证的AppID，但是图片分享也不能调起是为什么

**Comment by shexiaoheng** [comment]
@MrPluto 你的程序有AppID 么？ 打包apk的key跟开放平台一致么？

**Comment by pppluto** [comment]
是一样的。另外我是在开发模式下

**Comment by shexiaoheng** [comment]
@MrPluto 我的意思是你打包apk使用的签名文件（xx.keystore）是默认的debug还是自己创建的release？需要与微信开放平台填写的应用签名保持一致。

**Comment by pppluto** [comment]
你的意思是我需要打包APK，不能直接react-native run-android ?

**Comment by shexiaoheng** [comment]
@MrPluto 直接run的话也可以，你获取应用的签名，在微信开放平台上把应用签名改成跟你这程序一致就行，仅限于你一个人开发的情况下，最终发布还需要打包为release后再次获取应用的签名，修改微信开放平台的签名值。

**Comment by shexiaoheng** [comment]
@MrPluto 解决了么？

**Comment by pppluto** [comment]
那如何查看安卓签名？

**Comment by shexiaoheng** [comment]
去[微信开放平台](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419319167&token=&lang=zh_CN)下载[签名生成工具](https://res.wx.qq.com/open/zh_CN/htmledition/res/dev/download/sdk/Gen_Signature_Android221cbf.apk)生成，在微信开放平台填写信息的时候，应用签名下面有说明的，如果你看不懂，可以请教下你们那边做安卓的同事。

**Comment by pppluto** [comment]
是否指的证书指纹（SHA1）。我将我生成的keystore文件的证书指纹写入签名。绑定好我的package包。在installRelease模式下依然不能分享朋友圈。但是注册App是成功的

**Comment by shexiaoheng** [comment]
去[微信开放平台](https://open.weixin.qq.com/) --> 管理中心 --> 你的应用“操作”栏目下点击“查看” --> 找到“开发者信息”点击“修改” --> 找到“安卓应用”，有个应用签名输入框，输入框下边写的“`用于对当前应用进行二次身份校验，开发者可以使用签名生成工具直接从安装当前应用的手机中获取。应用签名由开发者签名该应用的keystore文件决定`。下载[微信提供的签名生成器](https://res.wx.qq.com/open/zh_CN/htmledition/res/dev/download/sdk/Gen_Signature_Android2.apk)对比下签名是否一致，也可以使用[新浪微博的签名生成工具](https://github.com/mobileresearch/weibo_android_sdk/blob/master/app_signatures.apk?raw=true)(带复制功能)

**Comment by pppluto** [comment]
:+1:

**Comment by naivehhr** [comment]
@shexiaoheng 
情景：react-native run-android 真机调试，[开始使用](https://github.com/beefe/react-native-wechat-android/blob/master/HELP.md#%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8) 中，可以注册和打开微信，但不能分享视频到微信，提示以下错误信息：

```
_share(){
        WeChat.sendReq(videoOptions,(err,sendOK) => {
          ToastAndroid.show(sendOK + '',ToastAndroid.SHORT); //=>false
          ToastAndroid.show(err + '',ToastAndroid.SHORT); //=>null
          });
  }
```

appid已设置，已将微信开放平台中应用的签名更改为使用签名生成工具获得的签名。

**Comment by shexiaoheng** [comment]
@naivehhr 你的apk包是打的release包吗？

**Comment by naivehhr** [comment]
@shexiaoheng 谢谢回复。
不是release包。我是直接用run-android直接安装到手机中的。然后用获取签名的工具获取的应用签名信息，在去开放平台更改签名信息。

**Comment by shexiaoheng** [comment]
@naivehhr 微信的开放平台不是立即生效的，可能过段时间才可以。打开微信是没有验证appid的，只有分享、登录、支付的时候才验证appid，分享文字可以的话，分享图片、音乐和视频都是OK的，我已经做过测试了，你仔细对比下签名信息是否一致，然后再试下。

**Comment by naivehhr** [comment]
@shexiaoheng 
好，我再试试。
还有个小问题，我已经设置了

```
-keep class com.tencent.mm.sdk.** {
   *;
}
```

但打包apk的时候还是会报错，暂且就先不设置代码混淆了。。。
![1](https://cloud.githubusercontent.com/assets/5243456/14343489/e6b4cc30-fcd3-11e5-8f3f-131d53bc829a.png)

**Comment by shexiaoheng** [comment]
@naivehhr 这句话只是保证微信的sdk不被混淆[微信文档](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=1417751808&token=&lang=zh_CN)。具体原因的话需要你根据报的错去定位，混淆这块确实容易出现很多问题。

**Comment by naivehhr** [comment]
@shexiaoheng 恩呢，Gmail 了你一下，方便的话查收哈。

**Comment by shexiaoheng** [comment]
@naivehhr 我的Gmail好像没有收到你的邮件诶

**Comment by naivehhr** [comment]
@shexiaoheng 这怎么回事...难道我进垃圾箱了?! QQ:1903283729 & Skype: Aran Hu你方便哪个加一下呗

**Comment by shexiaoheng** [comment]
@naivehhr 昨天下午加你qq到现在都没加上诶...

**Comment by naivehhr** [comment]
搞定!
1、分享功能注意:  thumbImage 图片大小限制；
2、支付功能注意:  H5调用支付API 和APP 调起支付接口的请求参数注意大小写,以免签名错误；

**Comment by shexiaoheng** [comment]
@naivehhr :+1:

**Comment by dongrenguang** [comment]
遇到一个很奇怪的问题：前两次分享是好好的，但如果再第三次分享就不成功了，监听到的“finishedShare”事件的返回值为false。关闭了应用，重新开启还是不行。楼上大神们有遇到过么？
