### ISSUE TITLE
WeChatModule.reactApplicationContext报错

### ISSUE THREAD

**Issue by peng051410** [beefe/react-native-wechat-android#7]
你好，我在使用你的插件时，在写WXEntryActivity时WeChatModule.reactApplicationContext报错，可否帮我看一下是什么问题，谢谢！

**Comment by shexiaoheng** [comment]
@peng051410 把错误详细日志贴上来呗，还有你用的RN的版本

**Comment by peng051410** [comment]
不好意思，是我弄错了，现在没有错了，sorry!
