### ISSUE TITLE
请问up主有微信支付的demo吗

### ISSUE THREAD

**Issue by rrrrrrex** [beefe/react-native-wechat-android#9]
我的统一下单接口已经成功获取prepayid，weChatPay方法也返回了成功，可是没有弹出来确认支付页面。。。支付的时候看到页面闪了一下，估计是调用确认页面的时候报错了？

**Comment by shexiaoheng** [comment]
检查下你包的签名

**Comment by rrrrrrex** [comment]
签名应该没有问题哦，因为我打包之后微信登录跟分享还是能正常使用的~

**Comment by shexiaoheng** [comment]
那你检查下你支付的参数，注意大小写，参考下这个[issues](https://github.com/beefe/react-native-wechat-android/issues/4)

**Comment by rrrrrrex** [comment]
可以了。。。就是参数大小写的问题。。。

**Comment by shexiaoheng** [comment]
👍
